<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net7.0;net8.0;net10.0</TargetFrameworks>
		<RuntimeIdentifiers>linux-x64;linux-arm64</RuntimeIdentifiers>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<PackageId>Cloudflare.QuicheNet.NativeAssets.Linux</PackageId>
		<Company>Cloudflare Inc.</Company>
		<Description>A delicious C# wrapper for Cloudflare's quiche library</Description>
		<PackageTags>quiche;networking;bindings;native;wrapper;quic</PackageTags>
		<PackageLicenseExpression>BSD-2-Clause</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/IsaMorphic/Cloudflare.QuicheNet</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<IncludeBuildOutput>false</IncludeBuildOutput>
	</PropertyGroup>


	<ItemGroup>
		<Compile Remove="runtimes/**" />
		<EmbeddedResource Remove="runtimes/**" />
		<None Remove="runtimes/**" />
	</ItemGroup>

	<PropertyGroup>
		<RustTargetTriple Condition="'$(RuntimeIdentifier)' == 'linux-x64'">x86_64-unknown-linux-gnu</RustTargetTriple>
		<RustTargetTriple Condition="'$(RuntimeIdentifier)' == 'linux-arm64'">aarch64-unknown-linux-gnu</RustTargetTriple>
		<RustLibraryFileName Condition="'$(RuntimeIdentifier)' == 'linux-x64'">libquiche_bindgen.so</RustLibraryFileName>
		<RustLibraryFileName Condition="'$(RuntimeIdentifier)' == 'linux-arm64'">libquiche_bindgen.so</RustLibraryFileName>
	</PropertyGroup>

	<ItemGroup>
		<RustTargetOutput Include="../quiche-bindgen/target/$(RustTargetTriple)/release/$(RustLibraryFileName)" />
		<NativeLibs Include="runtimes/**" />
		<None Include="@(NativeLibs)" PackagePath="runtimes/">
			<Pack>true</Pack>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MinVer" Version="7.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<Target Condition="'$(RuntimeIdentifier)' != ''" Name="rustc" BeforeTargets="PreBuildEvent">
		<Exec WorkingDirectory="../quiche-bindgen" Command="rustup target add $(RustTargetTriple)" />
		
		<Exec WorkingDirectory="../quiche-bindgen" Command="cargo cross build --target $(RustTargetTriple) --profile release" />

		<Copy SourceFiles="@(RustTargetOutput)" DestinationFolder="runtimes/$(RuntimeIdentifier)/native" />
	</Target>
</Project>