<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net7.0;net8.0;net10.0;net10.0-windows;net10.0-macos;net10.0-android;net10.0-ios</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<OutputType>Library</OutputType>
		<MinVerDefaultPreReleaseIdentifiers>preview.0</MinVerDefaultPreReleaseIdentifiers>
		<IsNuGetBuild>false</IsNuGetBuild>
	</PropertyGroup>

	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<PackageId>Cloudflare.QuicheNet</PackageId>
		<Company>Cloudflare Inc.</Company>
		<Description>A delicious C# wrapper for Cloudflare's quiche library</Description>
		<PackageTags>quiche;networking;bindings;native;wrapper;quic</PackageTags>
		<PackageLicenseExpression>BSD-2-Clause</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/IsaMorphic/Cloudflare.QuicheNet</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<None Include="../LICENSE.txt" Pack="true" PackagePath="/" />
		<None Include="../README.md" Pack="true" PackagePath="/" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="NativeMethods.g.cs" />
		<Compile Include="NativeMethods.g.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="csbindgen" Version="1.9.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="MinVer" Version="7.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0' Or '$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="System.IO.Pipelines" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Condition="'$(TargetFramework)' == 'net10.0' Or '$(TargetFramework)' == 'net8.0' Or '$(TargetFramework)' == 'net7.0'"
			Include="../Cloudflare.QuicheNet.NativeAssets.Linux/Cloudflare.QuicheNet.NativeAssets.Linux.csproj">
			<ReferenceOutputAssembly>$(IsNuGetBuild)</ReferenceOutputAssembly>
		</ProjectReference>
		<ProjectReference Condition="'$(TargetFramework)' == 'net10.0' Or '$(TargetFramework)' == 'net8.0' Or '$(TargetFramework)' == 'net7.0'"
			Include="../Cloudflare.QuicheNet.NativeAssets.macOS/Cloudflare.QuicheNet.NativeAssets.macOS.csproj">
			<ReferenceOutputAssembly>$(IsNuGetBuild)</ReferenceOutputAssembly>
		</ProjectReference>
		<ProjectReference Condition="'$(TargetFramework)' == 'net10.0' Or '$(TargetFramework)' == 'net8.0' Or '$(TargetFramework)' == 'net7.0'"
			Include="../Cloudflare.QuicheNet.NativeAssets.Win32/Cloudflare.QuicheNet.NativeAssets.Win32.csproj">
			<ReferenceOutputAssembly>$(IsNuGetBuild)</ReferenceOutputAssembly>
		</ProjectReference>
		<ProjectReference Condition="'$(TargetFramework)' == 'net10.0-windows'"
			Include="../Cloudflare.QuicheNet.NativeAssets.Win32/Cloudflare.QuicheNet.NativeAssets.Win32.csproj">
			<ReferenceOutputAssembly>$(IsNuGetBuild)</ReferenceOutputAssembly>
		</ProjectReference>
		<ProjectReference Condition="'$(TargetFramework)' == 'net10.0-macos'"
			Include="../Cloudflare.QuicheNet.NativeAssets.macOS/Cloudflare.QuicheNet.NativeAssets.macOS.csproj">
			<ReferenceOutputAssembly>$(IsNuGetBuild)</ReferenceOutputAssembly>
		</ProjectReference>
		<ProjectReference Condition="'$(TargetFramework)' == 'net10.0-android'"
			Include="../Cloudflare.QuicheNet.NativeAssets.Android/Cloudflare.QuicheNet.NativeAssets.Android.csproj">
			<ReferenceOutputAssembly>$(IsNuGetBuild)</ReferenceOutputAssembly>
		</ProjectReference>
		<ProjectReference Condition="'$(TargetFramework)' == 'net10.0-ios'"
			Include="../Cloudflare.QuicheNet.NativeAssets.iOS/Cloudflare.QuicheNet.NativeAssets.iOS.csproj">
			<ReferenceOutputAssembly>$(IsNuGetBuild)</ReferenceOutputAssembly>
		</ProjectReference>
	</ItemGroup>
</Project>